// Icon mapping from Lucide icon names to emojis
export const iconToEmoji: Record<string, string> = {
  'dumbbell': '🏋️',
  'book-open': '📖',
  'heart': '❤️',
  'leaf': '🍃',
  'droplets': '💧',
  'sun': '☀️',
  'moon': '🌙',
  'brain': '🧠',
  'apple': '🍎',
  'tree': '🌳',
  'flower2': '🌸',
  'waves': '🌊',
  'mountain': '⛰️',
  'sparkles': '✨',
  'target': '🎯',
  'smile': '😊',
  'coffee': '☕',
  'music': '🎵',
  'camera': '📷',
  'pen-tool': '✏️',
  'gamepad-2': '🎮',
  'smartphone': '📱',
  'car': '🚗',
  'plane': '✈️',
  'home': '🏠',
  'star': '⭐',
  'zap': '⚡',
  'fire': '🔥',
  'snowflake': '❄️',
  'clock': '⏰',
  'calendar': '📅',
  'gift': '🎁',
  'trophy': '🏆',
  'medal': '🏅',
  'flag': '🚩',
  'rocket': '🚀',
  'diamond': '💎',
  'gem': '💍',
  'key': '🔑',
  'shield': '🛡️',
  'sword': '⚔️',
  'bow': '🏹',
  'anchor': '⚓',
  'umbrella': '☂️',
  'balloon': '🎈',
  'confetti': '🎊',
  'party-popper': '🎉',
};

export function getEmojiForIcon(iconName: string): string {
  return iconToEmoji[iconName] || '🎯';
}